In [1]:
# Machine Learning in Finance 
# Week 1
# My SID : 2546621   'Last 2 digits: 21', we'll use 21 elements

import numpy as np

In [2]:
array = np.arange(21)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# Changing array to a 2D array with 1 row
array = array.reshape(1, -1)
print(array)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]


In [4]:
# Save the original array to a different array
diff_array = array
print(diff_array)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]


In [5]:
# shape of the diff_array
print(diff_array.shape)

(1, 21)


In [ ]:
# Machine Learning in Finance 
# Week 1
# My SID : 2546621   'Last 2 digits: 21', we'll use 21 elements

import numpy as np

# Making a Maxtrix with 21 Elements
array = np.arange(21)
print("Original Matrix :")
print(array)

# Changing the 2D Matrix with 1 Row
array = array.reshape(1, -1)
print("\n 2D array with 1 row : ")
print(array)

# Saving the original array to a different array
diff_array = array
print("\n Coppied Array :")
print(diff_array)

# Shape of the diff_array ?
print("\n Shape of the diff_array")
print(diff_array.shape)

Original Matrix :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 2D array with 1 row : 
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]

 Coppied Array :
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]

 Shape of the diff_array
(1, 21)
